"""add new field into notification

Revision ID: 68d77fcd6e16
Revises: 
Create Date: 2026-04-03 01:19:36.404864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68d77fcd6e16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('app_name', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'app_name')
    # ### end Alembic commands ###
